[tools]
python = "3.14"
uv = "latest"

[tasks."marimo:run"]
run = 'uv run marimo run --watch notebook.py'

[tasks."dev:watch"]
run = 'uv run marimo edit --watch --mcp --no-token notebook.py'

[tasks.ci]
hide = true
run = 'docker build -t fish-length .'